### ISSUE TITLE
Codespell report for "pound" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [graygnuorg/pound#12]
First of all, many years ago I benefited a lot from this great software. Thanks for that!

Here now as a very small contribution a codespell report for the current release:

&nbsp; https://fossies.org/linux/www/pound/codespell.html
 
Ok, no serious spelling errors (in the file ChangeLog probably even not correctable), but still three small errors in the manual page, which are thus also visible to users.

**Comment by graygnuorg** [comment]
Thank you. Fixed these in commit 11e05debe9.

**Comment by jschleus** [comment]
Just the small information that the result of a new run for the just released Pound version 4.12 is now available via the above URL (nothing exciting).

**Comment by graygnuorg** [comment]
Thanks a lot! Fixed in 074afeb061.
