### ISSUE TITLE
Create release of prerelease versions?

### ISSUE THREAD

**Issue by realsimix** [graygnuorg/pound#14]
Hi Sergey,

Would it be possible that you create a release of prerelease versions like 4.8.91? Since I'm maintaining RPM packages also for older distributions, it would make it easier for me to create such prereleases and test them. Problem is, the whole GNU auto* stuff is not new enough on such systems.

Thanks,
Simon

**Comment by graygnuorg** [comment]
Hi Simon,

Thanks for pinging me :)

> Would it be possible that you create a release of prerelease versions
> like 4.8.91?

Yes, given the amount of changes and prior testing, it merits a release.
I have released version 4.9.

Regards,
Sergey

**Comment by realsimix** [comment]
Thanks for version 4.9, all builds are fine.

BTW, you may want to change this:

```
--- README.md.orig	2023-08-23 09:18:16.449935410 +0200
+++ README.md	2023-08-23 09:19:16.517202950 +0200
@@ -82,8 +82,8 @@
 If you cloned __pound__ from the repository, you will need the
 following tools in order to build it:
 
-* [GNU Autoconf](http://www.gnu.org/software/automake), version 2.69 or later.
-* [GNU Automake](http://www.gnu.org/software/autoconf), version 1.15 or later.
+* [GNU Autoconf](http://www.gnu.org/software/automake), version 2.71 or later.
+* [GNU Automake](http://www.gnu.org/software/autoconf), version 1.16.5 or later.
 
 First, run
```
Thanks,
Simon

**Comment by graygnuorg** [comment]
Simon Matter ***@***.***> ha escrit:

> BTW, you may want to change this:

Ah, sure. Thanks for pointing that out.

Regards,
Sergey
