### ISSUE TITLE
Backed does not come back from dead status

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#16]
One of our backend (Tomcat on Windows) does not come back from the "dead" status when, for some reasons, it becomes unreachable for some time.
We do not have set the "Alive" parameter.
The only way to get it back working is to restart pound.
Is there anything we can check?

**Comment by graygnuorg** [comment]
> Is there anything we can check?

Yes, look for warning messages in pound log that begin with
"connect_nb:".  These should appear each 30 seconds (the default
alive interval).  Do you see any?

Regards,
Sergey

**Comment by abaldoni** [comment]
For that host, I can see them only twice, at 30 seconds from each other, but after those there are no more of them.

Regards,
Alessandro

**Comment by graygnuorg** [comment]
abaldoni ***@***.***> ha escrit:

> For that host, I can see them only twice, at 30 seconds from each
> other, but after those there are no more of them.

What messages do you see?

**Comment by abaldoni** [comment]
Hello Sergey,
  Sep  3 07:07:42 pound-101 pound[969]: (7fe30fca7640) connect_nb: error after getsockopt: Connection refused
  Sep  3 07:08:12 pound-101 pound[969]: (7fe312ce5640) connect_nb: error after getsockopt: Connection refused

and after that timestamp no more.

**Comment by graygnuorg** [comment]
Thanks for additional info.  Can you show me the "Service" section
where this backend is defined?  Is that the only backend that behaves
this way?

**Comment by graygnuorg** [comment]
> The configuration is utterly simple:

Indeed.  That's weird.

Do you have "Control" configured? If so, have you examined the status
of this backend using poundctl list?

**Comment by abaldoni** [comment]
I indeed have Control configured but never used poundctl.
If you agree, you can close this issue as "not planned" while I'll be monitoring the problem and eventually get back to you.

**Comment by graygnuorg** [comment]
> I indeed have Control configured but never used poundctl.
> If you agree, you can close this issue as "not planned" while I'll be
> monitoring the problem and eventually get back to you.

Ok.  If it occurs again, please be sure to include the output of
"poundctl list" and a couple of lines from the log file, that follow
the last connect_nb message (only warnings and errors are of interest,
normal "access-style" logging is not).

Regards,
Sergey

**Comment by nagyrobi** [comment]
I ran into the same issue recently. It was a linux backend. Had to restart pound for the fix.

**Comment by graygnuorg** [comment]
Thanks for the feedback.  Can you give some more detail please: version
of pound, number of backends in the service, anything else that you
think might be of interest?

**Comment by nagyrobi** [comment]
In my case this is pound (pound) 4.6.90.
Have 9 services in total, each with one backend configured.

```
ListenHTTP
	Service
		Host "my.domain.tld"
		Redirect 301 "https://my.domain.tld"
	End
End

Service
	Host "my.domain.tld"
	BackEnd
		Address 192.b.x.y
		Port    zzzzz
		WSTimeOut	60
	End
End
```

**Comment by graygnuorg** [comment]
Was there anything in the pound log? Things of interest are messages beginning with "connect_nb", or any error messages?

**Comment by nagyrobi** [comment]
1. No Daemon configuration specified in the config file (according to the doc, it runs as daemon as default)
2. `LogLevel	0`
3. no command line options, it's invoked by the `rc.d` script as `/usr/local/sbin/pound`

**Comment by graygnuorg** [comment]
Thanks. Then, I suppose, you should have seen several `connect_nb:` messages in your pound log, and then nothing up to the moment of pound restart. Is that so?

**Comment by nagyrobi** [comment]
Yep indeed, hundreds of them:


Sep 12 15:45:28 | pound | 9032 | (800a79d00) connect_nb: error after getsockopt: Connection refused
-- | -- | -- | --
Sep 12 15:45:13 | pound | 9032 | (800a79d00) connect_nb: error after getsockopt: Connection refused
Sep 12 15:44:58 | pound | 9032 | (800a79d00) connect_nb: error after getsockopt: Connection refused
Sep 12 15:44:43 | pound | 9032 | (800a79d00) connect_nb: error after getsockopt: Connection refused
Sep 12 15:44:28 | pound | 9032 | (800a79d00) connect_nb: error after getsockopt: Connection refused

**Comment by graygnuorg** [comment]
Ok. Last (hopefully) question: what was the time difference between last of them and the time when you restarted pound?

**Comment by abaldoni** [comment]
I have a (maybe) new insight: the backend that does not get resurrected is used multiple times in different listeners.
Today, I got the following status (grepped from poundctl):

        0. backend http 192.168.0.61:8280 5 alive active
        0. backend http 192.168.0.61:8280 5 alive active
        0. backend http 192.168.0.61:8280 5 dead active
        0. backend http 192.168.0.61:8280 5 alive active

As always I had to restart pound to get it 'alive' again. Using 'poundctl disable/enable' did not work.

**Comment by nagyrobi** [comment]
> Ok. Last (hopefully) question: what was the time difference between last of them and the time when you restarted pound?

Didn't catch that info. Logs rotated since then...

**Comment by graygnuorg** [comment]
Hi Alessandro,

> I have a (maybe) new insight: the backend that does not get
> resurrected is used multiple times in different listeners.
> Today, I got the following status (grepped from poundctl):

That's interesting, thanks for the info.  As a matter of fact,
for pound these are different backends, although having the same
target address.  Nevertheless, it may indeed be important.

Were other backends (among these) operational while that one remained
in the dead state?  Pound marks the backend as dead only if there was
an unsuccessful attempt to connect to it, so it is important to know
if any requests were successfully served by these while the other one
remained inactive.

Another question: according to logs, what was the time difference
between the moment you restarted pound and the most recent 'connect_nb:'
message?  Did pound serve any other requests in between?

Regards,
Sergey

**Comment by StomproLARL2023** [comment]
Hello, I think I'm also noticing this issue.  

pound 4.9
Launched from systemd

One interesting thing is that the websocketd backend was redetected as alive once its server was brought back up, but the http and https services were not.

Set 3 backends for 3 services, https, http and websockets on port 7682.

Only had one live backend server but entries for the future ones were added.  Only the active ones showed as alive.  Brought up the new backend server and pound only detected that the websockd service was back up.  http and https just showed "dead active".

Tried using poundctl to disable and enable them, but that didn't seem to help.

**Comment by graygnuorg** [comment]
Thanks for the feedback.  Please try commit bfd8c1de94e4e5751c7b1d703b183468d27e60db.

**Comment by graygnuorg** [comment]
@abaldoni , @nagyrobi , Any news?

**Comment by nagyrobi** [comment]
Not yet, as I need to set up environment to compile under bsd.

**Comment by abaldoni** [comment]
I deployed the commit last saturday and, as of today, we experienced no problems at all. 👍

**Comment by graygnuorg** [comment]
In the lack of further info, I'm closing that as completed.
