### ISSUE TITLE
[FR] response headers modification

### ISSUE THREAD

**Issue by beelze** [graygnuorg/pound#22]
`pound` has a good and sufficient mechanism to manipulate _request_ headers. Though, sometimes may be needed to change _response_ headers too (it may be needed especially when there is no way to modify backend server behaviour or when in need of  removing «improper» headers, if any.

It would be nice to have a possibility to use appropriate directives inside `Backend` section (e.g. `SetResponseHeader "name: value"` and `DeleteResponseHeader [options] "pattern"`) – with the same logic as for request headers (include `Rewrite` conditionals)

**Comment by graygnuorg** [comment]
This feature is available in version 4.10. See "Response header modification" in https://github.com/graygnuorg/pound/releases/tag/v4.10.

**Comment by beelze** [comment]
Sorry, I was reading not up-to-date [documentation](https://www.gnu.org.ua/software/pound/pound.html). FR is already implemented in 4.10.

**Comment by graygnuorg** [comment]
My bad. Thanks for reporting it. I've updated the docs.
