### ISSUE TITLE
"error copy client cont" error

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#27]
Using pound 4.9.90 and upgraded to 4.11.90.

We started seeing more and more of the following errors for a specific backend:

e500 for [ext ip address] error copy client cont to [backend address]/POST /EWS/mrsproxy.svc HTTP/1.1: Connection timed out (10.038 sec)

Can you help us understand what does the error mean and where the time out is set?

This is the configuration stanza in use:

        Service
                HeadRequire "Host: .*redacted*"
                URL ".*/(autodiscover|ecp|ews|EWS|mapi|Microsoft-ActiveSync|oab|owa|rpc).*"
                IgnoreCase 1
                BackEnd
                        HTTPS
                        Address redacted
                        Port 443
                        TimeOut 180
                End
        End

Regards,
AB

**Comment by graygnuorg** [comment]
This message means that the client didn't send the content of the request (as announced by the Content-Length header) within the client timeout. The timeout is set by the [Client](https://www.gnu.org.ua/software/pound/manual/Listener_002dspecific-limits.html#index-Client-1) statement in the `ListenHTTP` . The default is 10 seconds.

**Comment by abaldoni** [comment]
Hi, yes the error is in both version 4.9.90 and 4.11.90.
Unfortunately we cannot say whether it was present in earlier versions: we can only say that the backend seemed to work better in the past.

**Comment by graygnuorg** [comment]
And you can't reproduce it, can you?

**Comment by abaldoni** [comment]
I a certain sense I can. 
The backend connects to a Microsoft Exchange hybrid mode server and the error occurs when we need to migrate a mailbox from the on-premise server to the Microsoft cloud.
I tried again a few hours ago and the problem occurred again.

**Comment by graygnuorg** [comment]
That's great. A couple of questions then:
1. Is it possible that this migration sometimes takes more than 10 seconds?
2. Have you tried to raise the client timeout? If not, can you please try and see if this helps?
3. Do you see anything special in the backend logs?

**Comment by abaldoni** [comment]
The "time" factor is quite unclear to me.
The job gets scheduled on the Microsoft cloud which tries to execute it at its own pace.
I'll try to increate the client timeout since 10 secs is definitely too low.
The backend logs are unfortunately of no use in diagnosing the problem.
I'll be back with further details.

Thanks!

**Comment by graygnuorg** [comment]
In the meantime you might wish to pull the commit 3996e21af4cd1c155cb08272e8f9d0464eb05518 which improves diagnostic messages a bit.

**Comment by abaldoni** [comment]
Hi, for this specific case we decided to move our Exchange from hybrid to full cloud so we won't be using this backend anymore.
Since no other backend presents the problem I'm going to close this issue.

Thanks!
