### ISSUE TITLE
Unable to use the same backend for different virtual hosts

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#29]
Hi, I have an Apache backend which serves multiples sites on the same IP on port 80 but on different virtual hosts via the ServerName directive:
```
    http://app1.domain.local
    http://app2.domain.local
```
and so on.
I'm unable to make this configuration work with pound.
I defined the following backends:
```
  BackEnd "App1"
          Address app1.domain.local
          Port 80
  End
  BackEnd "App2"
          Address app2.domain.local
          Port 80
  End
```

This is not working because pound _talks_ with the backend using its IP.

Is there any way to handle this kind of configuration?

Kind regards,
A.

**Comment by graygnuorg** [comment]
Use the `ServerName` directive (available since version 4.11:

```
BackEnd "App1"
          Address app1.domain.local
          Port 80
          ServerName "app1.domain.local"
End
```

Otherwise, you can also use the `SetHeader` directive in  `Service`  section which encloses that backend:

```
Service 
   ...
   SetHeader "Host: app1.domain.local"
   Backend
      ...
   End
End
```

**Comment by graygnuorg** [comment]
A correction: `ServerName` is available for use in HTTPS backends only. For plain HTTP backends, you'll have to use `SetHeader`.

**Comment by abaldoni** [comment]
Thank you, it worked like a charm!
