### ISSUE TITLE
OpenSSL 3 misses dhparam -C option to print C code

### ISSUE THREAD

**Issue by egc112** [graygnuorg/pound#3]
OpenSSL 3 misses dhparam -C option to print C code.  

Resulting error:  
`make -C pound CC="ccache arm-linux-uclibc-gcc" make[1]: Entering directory '/media/egc/linuxdata/ddwrt/src/router/pound' openssl dhparam -5 -C -noout 512 > dh512.h `

Code is in Makefile.am

**Comment by graygnuorg** [comment]
Fixed by commits 1bae081e29 and 1748d062ca
