### ISSUE TITLE
Pound 4.12 segfaults with libpcre2

### ISSUE THREAD

**Issue by johndoe7000** [graygnuorg/pound#33]
Hello,

pound 4.12 sporadically segfaults on Debian 12 (bookworm) with libpcre2...

kernel: [   32.075593] pound[403]: segfault at 7f4e7c021000 ip 00007f4e9d5e00cd sp 00007f4e9d1720b0 error 4 in libpcre2-8.so.0.11.2[7f4e9d587000+6b000] likely on CPU 1 (core 1, socket 0)
kernel: [ 7541.154310] pound[13919]: segfault at 7f5b67ffffff ip 00007f5baabe39fb sp 00007f5ba9f52060 error 4 in libpcre2-8.so.0.11.2[7f5baab87000+6b000] likely on CPU 0 (core 0, socket 0)

I've compiled pound from Debian Sid... thank you, that this masterpiece is part of Debian again:)

If I compile pound from Debian Sid with libpcre3, which is described with "Old Perl 5 Compatible Regular Expression Library" than pound runs rock solid.

Sadly I currently use pound 4.12 in production environment and cannot simply do testing because of reachability.

libpcre2 on Debian 12 is currently in version 10.42-1 (New Perl Compatible Regular Expression Library)
libpcre3 on Debian 12 is currently in version 2:8.39-15 (Old Perl 5 Compatible Regular Expression Library)

Do you have a clue what is going on?
I feel in my guts that the new libpcre2 is "not that compatible" as the older libpcre3 (despite the package versioning 2 vs 3).

**Comment by graygnuorg** [comment]
I have received several reports indicating that libpcre2 causes pound to
segfault.  Can you give me some detail about your pound.cfg file (most
importantly, the regexps used in it).  Perhaps it will help me reproduce
that.

Regards,
Sergey

**Comment by johndoe7000** [comment]
Hello Sergey,

let me explain first...
Our last pound installations where all 2.8, we ommited 3.x because of the move to YAML configuration, which didn't work in every aspect.

Our pound configurations are all quite easy... mostly...

        Service
            Header "Host:.*test1.example.com.*"
            Redirect "https://test2.example.com/"
        End
        Service
            Header "Host:.*test2.example.com.*"
                BackEnd
                        Address x.x.x.x
                        TimeOut 60
                        Port    80
                End
                Session
                        Type IP
                        TTL 300
                End
        End

Using ".*" is the only regexp syntax we use but without your new implementation with "-re" with Header oder Host.
What might be interesting is that we still use "IgnoreCase 1" in every pound installtion in global section.

Hope this helps.

**Comment by graygnuorg** [comment]
Thanks. I was able to reproduce the bug using a simplest regexp: the key was to send several requests simultaneously. The traces show that libpcre2 (or, at least prce2posix) functions are not thread-safe: the coredump occurs in pcre2_match_8 when it is called simultaneously from several threads.

The solution is to recompile pound with the --disable-pcreposix option.

I am going to remove the pcre2 support from the next release.

**Comment by johndoe7000** [comment]
Good catch, Sergey.

This also explains why my installation with libpcre2 on my private server never crashed... this machine has only "one" virtual cpu core.
I think the best way would be to inform pcre2 developers to look at that problem since libpcre3 (aka prce1) is EOL...
http://www.pcre.org/

Regards,
Darius

**Comment by johndoe7000** [comment]
FYI, reported an issue to pcre2 devs...
https://github.com/PCRE2Project/pcre2/issues/438

**Comment by graygnuorg** [comment]
As a matter of fact, in the recent documentation to pcre2posix (https://pcre2project.github.io/pcre2/doc/html/pcre2posix.html) it is stated explicitly, that "The functions described here are NOT thread-safe, and should not be used in multi-threaded applications". So, the only way to use pcre2 would be to rewrite regex handling code to use basic pcre2 API (which is, presumably, thread-safe), instead of pcre2posix.

**Comment by johndoe7000** [comment]
What a shame I didn't read that. I've closed the issue for pcre2.
Thanks  a lot.

**Comment by graygnuorg** [comment]
I have pushed the following change: https://github.com/graygnuorg/pound/commit/a3d2b9e0d41c2d5c0487dba0ea5d5178cdfae9c7. My tests show that it fixes the problem. Please, give it a try.

**Comment by johndoe7000** [comment]
OK, I've reinstalled libpcre2-dev on one of our productive Pound reverse proxies and recompiled with it.

"ldd /usr/sbin/pound" clearly shows that libpcre2posix is not a shared library any more...
linux-vdso.so.1 (0x00007fffd6a69000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fb5f7ba3000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fb5f7afa000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fb5f7600000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fb5f7abe000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb5f741f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb5f7c7f000)

Will observe now and report back in a couple of days.

**Comment by johndoe7000** [comment]
Works as expected, thank you.
