### ISSUE TITLE
Testsuite fails since commit f1e5467fa2ac4baf8f60ff75833b06f541916832

### ISSUE THREAD

**Issue by johndoe7000** [graygnuorg/pound#38]
Hello,

nearly all tests (make check) fail since commit f1e5467fa2ac4baf8f60ff75833b06f541916832.

Howto to reproduce...
./bootstrap
./configure --disable-dynamic-backends
make
make check

Snippet...
## ---------------------- ##
  1: Configuration file syntax                       ok
  2: Traditional log levels (compilation)            ok
  3: Basic request processing                        FAILED (echo.at:18)
  4: Traditional log levels (output)                 FAILED (loglevrun.at:46)
  5: HTTP log formats                                FAILED (logfmt.at:40)
  6: Log suppression                                 FAILED (logsup.at:44)
  7: xHTTP                                           FAILED (xhttp.at:37)
  8: CheckURL                                        FAILED (checkurl.at:50)
  9: Custom Error Response                           FAILED (errfile.at:29)
 10: MaxRequest                                      FAILED (maxrequest.at:19)
 11: MaxURI                                          FAILED (maxuri.at:19)
 12: RewriteLocation                                 FAILED (rewriteloc.at:20)
 13: RewriteLocation (https)                         FAILED (rewriteloc_https.at:12)
 14: Named backends                                  FAILED (nb.at:18)
 15: Chunked encoding                                FAILED (chunked.at:19)
 16: Invalid Transfer-Encoding headers               FAILED (invenc.at:21)

My system is...
Debian 12 Bookworm.

Since I don't use dynamic-backends "libadns1-dev" and "libnet-dns-perl" is not installed.

**Comment by graygnuorg** [comment]
Please, make sure you have all dependencies necessary for testsuite properly installed. Take a look at README for a complete list. In particular this version requires JSON.pm, which wasn't needed earlier. Besides, to investigate the reasons of testsuite failure, I need a detailed info about it. Again, README explains in detail what is needed.

**Comment by johndoe7000** [comment]
Yes, you are right. The missing part was JSON.pm.
It seems it's not installed on Debian by default... "apt install libjson-perl"... solves the problem.
