### ISSUE TITLE
Problem building pound 4.15 on OEL 9.5

### ISSUE THREAD

**Issue by abaldoni** [graygnuorg/pound#40]
Hi, running ./boostrap on OEL 9.5 fails with the following message:

```
src/Makefile.am:48: error: library used but 'RANLIB' is undefined
src/Makefile.am:48:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/Makefile.am:48:   to 'configure.ac' and run 'autoconf' again.
tests/Makefile.am:150: error: Libtool library used but 'LIBTOOL' is undefined
tests/Makefile.am:150:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
tests/Makefile.am:150:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
tests/Makefile.am:150:   If 'LT_INIT' is in 'configure.ac', make sure
tests/Makefile.am:150:   its definition is in aclocal's search path.
autoreconf: error: automake failed with exit status: 1
```

I had to run the command libtoolize and rerun ./boostrap again.

**Comment by graygnuorg** [comment]
> Hi, running ./boostrap on OEL 9.5 fails with the following message:
> 
> src/Makefile.am:48: error: library used but 'RANLIB' is undefined
> src/Makefile.am:48:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'

This message means that you have obsolete version of libtool installed.
Bootstrapping requires sufficiently new versions of certain tools.
Currently these are: 

  autoconf 2.71
  automake 1.16.5
  libtool 2.4.6

Make sure the versions you have are not lower than these.
  
Notice also, that bootstrapping is needed only if you are installing
from git sources.  You don't need to run bootstrap when building a
packaged release, which you can grab from

https://github.com/graygnuorg/pound/releases/download/v4.15/pound-4.15.tar.gz
