### ISSUE TITLE
Small logging patch

### ISSUE THREAD

**Issue by realsimix** [graygnuorg/pound#9]
Hi Sergey,

Thanks a lot for continuing the pound project, nice to see the story is going on!

May I propose a small patch which slightly changes the logging?

The first changes affect the `http_log_1()` and `http_log_2()` where they write the response_code to the log instead of _what_?
In my logs I never see anything printed after the `-` so it ends up with simply two spaces. I thought it's better to have the HTTP status code there instead of nothing but I don't know what should be printed there instead.

From
`Apr  3 15:12:47 ns1 pound[15656]: 18.143.5.18 GET /mail/ HTTP/1.1 -  (abc.invoca.ch/- -> 18.161.91.34:8080) 0.018 sec
`
To
`Apr  3 15:12:47 ns1 pound[15656]: 18.143.5.18 GET /mail/ HTTP/1.1 - 302 (abc.invoca.ch/- -> 18.161.91.34:8080) 0.018 sec
`

The second change is to bring the terminating thread message in line with other messages about threads:

From
`Apr  3 15:12:48 ns1 pound[15656]: (7f404797e700) e503 no service "GET /favicon.ico HTTP/1.1" from 18.143.5.18 abc.invoca.ch`
`Apr  3 15:12:48 ns1 pound[15656]: thread 7f404797e700 terminating on idle timeout
`

To
`Apr  3 15:12:48 ns1 pound[15656]: (7f404797e700) e503 no service "GET /favicon.ico HTTP/1.1" from 18.143.5.18 abc.invoca.ch`
`Apr  3 15:12:48 ns1 pound[15656]: (7f404797e700) terminating thread on idle timeout
`

Thanks,
Simon

[pound-4.7-logmsg.patch.txt](https://github.com/graygnuorg/pound/files/11138724/pound-4.7-logmsg.patch.txt)

**Comment by graygnuorg** [comment]
Hi Simon.

Thanks for the patch.  Regarding http_log_[12], the empty space you noticed is due to the bug introduced not so long ago (commit 2136f919). It is the response line that should have been there. I fixed this in commit 1a53db026a563c0602077bebd4fde393ba2056e9. I have applied the suggested change to the thread terminating message (c086716c8d490e877f8bb541ab77b5ac5da93035). Please, pull.

**Comment by realsimix** [comment]
Thanks for the update, logging works fine now!
